### ISSUE TITLE
Discussion - remove directions component from frontend?

### ISSUE THREAD

**Issue by abell95** [osu-cascades/hdffa-food-finder#14]
Open to discussion.

Reasons for removing:
* Primary purpose of app is to see closest HDFFA partners and get info. Clicking around the map will create directions, which is probably not helpful for people trying to do this.

Alternatively, keep the function but change how it is accessed (e.g. button in top-right corner with text input)

**Comment by lauriewayne** [comment]
Here is a use case: I am going to Prineville from Bend and I want to know what farms are there, App will tell me what's around me, but I zoom out, find Bluestone Natural Farms in Powell Butte on the way to Prineville, and want to get directions to there. Will the app let me do that? It's conceivable that I would want directions to something a mile away as well. I can see where the directions may be "manually" called by clicking on the address and then pasting it into Waze or whatever. Would be interested in the pros and cons of these two approaches (maybe do a quick screen capture of what it looks like now?)

**Comment by abell95** [comment]
I'll get a screen capture for you of how it looks now. Something I was considering was, when you click on a partner and get the popup, there's a "get directions" button at the bottom of the popup that creates a route from where the user is at to the partner's listed address. I cannot ensure that this is doable without some research and we need to push through more tasks before getting to it, of course.

While we're discussing it, how would you like us to handle adding partners with no listed address? At present we cannot place them on the map.
